//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripTravelSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.LikeDislikes = new HashSet<LikeDislike>();
            this.PostsRequests = new HashSet<PostsRequest>();
            this.SavedPosts = new HashSet<SavedPost>();
        }
    
        public int postID { get; set; }
        public string tripTitle { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime tripDate { get; set; }
        public string tripImage { get; set; }
        public string tripDescription { get; set; }
        public string tripPrice { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime postDate { get; set; }
        public int uID { get; set; }
        public Nullable<int> numberOfLikes { get; set; }
        public Nullable<int> numberOfDisLikes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeDislike> LikeDislikes { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostsRequest> PostsRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedPost> SavedPosts { get; set; }
    }
}
